#!/bin/bash
if [[ ! $1 ]];
then
	echo "Usage: stonks STOCK_ID (stonks AAPL; stonks GME)"
	echo "Flags: -c = show price of crypto (stonks -c XMR)"
fi
if [[ $1 != "-c" ]];
then
	website=$(curl -s https://finance.yahoo.com/quote/$1 | tr -d '\0')
else
	website=$(curl -s https://finance.yahoo.com/quote/$2-USD | tr -d '\0')
fi
mclose=$(echo $website | grep -Po 'data-reactid="37">\K[^<]+' | head -n 1)
if [[ $mclose =~ "^[0-9]*.[0-9]*$" ]];
then
    echo $mclose
else
    echo $website | grep -Po 'data-reactid="32">\K[^<]+' | head -n 1
fi
